In [1]:
import numpy as np
abc = [1,2,3,4,5,8,9,10]
sample = np.array(abc)

In [2]:
import numpy as np
x = ['a','b','c']
y = np.array(x)


In [3]:
AA = ([1,2,3],[4,5,6])
np.array(AA)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arrange(5,9)


AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
np.array.arrange(1,5)

AttributeError: 'builtin_function_or_method' object has no attribute 'arrange'

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((6), dtype=int)

array([0, 0, 0, 0, 0, 0])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.linspace(5)

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In [14]:
np.random.rand(2,4)

array([[0.87694665, 0.02423565, 0.38131508, 0.29252594],
       [0.38445974, 0.52508552, 0.34590668, 0.71420425]])

In [18]:
a = np.random.randn(2,4)
a

array([[ 0.0068824 , -1.31239465,  0.12573964, -0.87126663],
       [-0.6058278 ,  1.33044475, -0.41547909, -0.70673828]])

In [19]:
a.argmin()

1

In [20]:
a.argmax()

5

In [21]:
a.dtype()

TypeError: 'numpy.dtype[float64]' object is not callable

In [22]:
a.T

array([[ 0.0068824 , -0.6058278 ],
       [-1.31239465,  1.33044475],
       [ 0.12573964, -0.41547909],
       [-0.87126663, -0.70673828]])

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])